stage_1:
  target: stage1.VAECommon
  params:
    resolution: 256
    channel_dim: 4
    downsample_factor: 8
    vae_config:
      target: ifid.vae.klvae.KLVAE
      params:
        embed_dim: 4
        ch_mult: [1, 2, 4, 4]
        use_pre_post: True
        ckpt_path: REPA-E/sdvae/sdvae-f8d4.pt

stage_2:
  target: stage2.models.DDT.DiTwDDTHead
  params:
    input_size: 32
    patch_size: [2, 2]
    in_channels: 4
    hidden_size: [1152, 2048]
    depth: [28, 2]
    num_heads: [16, 16]
    mlp_ratio: 4.0

conditioning:
  type: "text"
  cfg_dropout_prob: 0.1
  text_encoder:
    model_name: "Qwen/Qwen3-0.6B"
    max_length: 256
  arch:
      num_t_tokens: 4

transport:
  prediction: 'velocity'
  time_dist_type: 'logit-normal_0_1'

sampler:
  num_steps: 50

guidance:
  cfg:
    scale: 6.0
    t_min: 0.0
    t_max: 1.0

dataset:
  target: 'blip3o'
  type: 'wds'
  data_dir: "/data1/v-xutongda/datasets/blip3o-256"
  split: ["journeydb", "long-caption", "short-caption"]
  condition_type: "text"
  shuffle_buffer: 10000
  seed: 42
  shared_tmpdir: "~/tmp"

training:
  epochs: 10
  global_batch_size: 128
  grad_accum_steps: 1
  ema_decay: 0.9995
  num_workers: 4
  virtual_epoch_steps: 10000
  log_interval: 100
  checkpoint_interval: 1
  sample_every: 100
  clip_grad: 1.0
  global_seed: 42
  optimizer:
    lr: 2.0e-4
    betas: [0.9, 0.95]
    weight_decay: 0.0
  scheduler:
    type: linear
    warmup_epochs: 5
    decay_end_epoch: 100
    base_lr: 2.0e-4
    final_lr: 2.0e-5
    warmup_from_zero: false
  image_size: 256

eval:
  eval_interval: 10000
  eval_model: false
  eval_dir: "results/evals/stage2/training/t2i-vae"
  datasets:
    geneval:
      type: 'hf'
      data_dir: '/data1/v-xutongda/datasets'
      split: 'val'
      condition_type: 'text'
      metrics: ['geneval']
    dpgbench:
      type: 'hf'
      data_dir: '/data1/v-xutongda/datasets'
      split: 'val'
      condition_type: 'text'
      metrics: ['dpgbench']
    genaibench:
      type: 'hf'
      data_dir: '/data1/v-xutongda/datasets'
      split: 'val'
      condition_type: 'text'
      metrics: ['vqascore_clip-flant5-xxl']

misc:
  latent_size: [4, 32, 32]
  num_classes: 1000
  time_dist_shift_dim: 16384
  time_dist_shift_base: 4096

perceptual_loss:
  encoders: 'lpips,dinov2-vit-b'
  percep_loss_weights: [0.5, 0.05]

repa:
  use_repa: true
  use_reg: false
  reg_coeff: 0.0
  repa_layer_depth: 8
  repa_coeff: 0.5
  target_encoder: dinov2-vit-b
  target_encoder_resolution: 256
